services:
    backend:
        container_name: "pet-clinic-backend"
        image: costi0/pet-clinic-backend
        build: spring-petclinic-rest
        ports:
            - 9966:9966
        environment:
            DATABASE_URI: ("DATABASE_URI")

    frontend:
        container_name: "pet-clinic-frontend"
        image: costi0/pet-clinic-frontend
        build: spring-petclinic-angular
        ports:
            - 8080:8080
